ttbar_allhad: &ttbar_allhad
  name: ttbar_allhad
  pattern: Rel22_ttbar_AllHadronic/*.h5

global_cuts:
  train:
    - [eventNumber, "%10<=", 7]
  val:
    - [eventNumber, "%10==", 8]
  test:
    - [eventNumber, "%10==", 9]

# Not needed to do manually, features already available via ftag tools!
# light: &light
#   name: light
#   cuts:
#     - [HadronConeExclTruthLabelID, "<", 4]

# charm: &charm
#   name: charm
#   cuts:
#     - [HadronConeExclTruthLabelID, "==", 4]

# bottom: &bottom
#   name: bottom
#   cuts:
#     - [HadronConeExclTruthLabelID, "==", 5]

# tau: &tau
#   name: tau
#   cuts:
#     - [HadronConeExclTruthLabelID, "==", 15]

inclusive: &inclusive
  name: inclusive
  cuts: []

components:
  # - region:
  #     <<: *inclusive
  #   sample:
  #     <<: *ttbar_allhad
  #   flavours: [ujets]
  #   num_jets: 300_000

  # - region:
  #     <<: *inclusive
  #   sample:
  #     <<: *ttbar_allhad
  #   flavours: [cjets]
  #   num_jets: 200_000

  - region:
      <<: *inclusive
    sample:
      <<: *ttbar_allhad
    flavours: [bjets]
    num_jets: 1_000_000
    
  # - region:
  #     <<: *inclusive
  #   sample:
  #     <<: *ttbar_allhad
  #   flavours: [taujets]
  #   num_jets: 100_000

resampling:
  target: bjets
  method: none #countup #pdf
  sampling_fraction: 1 #auto
  variables:
    pt_btagJes:
      bins: [[20_000, 1_000_000, 28]]
    absEta_btagJes:
      bins: [[0, 2.5, 5]]
    #n_tracks:
    #  bins: [[0, 20, 20]]
    #nPrimaryVertices:
    #  bins: [[0, 50, 50]]
    # d0:
    #   bins: [[-1.0, 1.0, 20]]
    # z0SinTheta:
    #   bins: [[-1.0, 1.0, 20]]
    # dphi:
    #   bins: [[-1.0, 1.0, 20]]
    # deta:
    #   bins: [[-1.0, 1.0, 20]]
    # qOverP:
    #   bins: [[-1.0, 1.0, 20]]
    # IP3D_signed_d0_significance:
    #   bins: [[-5.0, 5.0, 20]]
    # leptonID:
    #   bins: [[-15, 15, 30]]
    # truthOriginLabel:
    #   bins: [[-15, 15, 30]]
    # truthVertexIndex:
    #   bins: [[0, 5, 5]]


global:
  batch_size: 10_000
  num_jets_estimate: 10_000
  base_dir: /gpfs/slac/atlas/fs1/d/bbullard/BjetRegression/
  out_dir: FTag_upp/Rel22_ttbar_AllHadronic_bjetonly
  ntuple_dir: Input_Ftag_Ntuples/

variables:
  jets:
    inputs:
      - pt_btagJes
      - eta_btagJes
      - n_tracks
      - nPrimaryVertices
    labels:
      - truthJetPt
      - HadronConeExclTruthLabelID

  tracks:
    inputs:
      - d0
      - z0SinTheta
      - dphi
      - deta
      - qOverP
      - eta
      - pt
      - IP3D_signed_d0_significance
      - IP3D_signed_z0_significance
      - phiUncertainty
      - thetaUncertainty
      - qOverPUncertainty
      - numberOfPixelHits
      - numberOfSCTHits
      - numberOfInnermostPixelLayerHits
      - numberOfNextToInnermostPixelLayerHits
      - numberOfInnermostPixelLayerSharedHits
      - numberOfInnermostPixelLayerSplitHits
      - numberOfPixelSharedHits
      - numberOfPixelSplitHits
      - numberOfSCTSharedHits
      - leptonID
    labels:
      - truthOriginLabel
      - truthVertexIndex
