ttbar_nonallhad: &ttbar_nonallhad
  name: ttbar_nonallhad
  # pattern: user.bbullard.410470.e6337_s3681_r13144_p5169.tdd.PHYSVAL_EMPFlow_jer.23_0_26.v2.1_output.h5/*.h5
  pattern: user.pbhattar.410470.e6337_s3681_r13144_p5169.tdd.PHYSVAL_EMPFlow_jer.23_0_26.24-05-16-T173804_output.h5/*.h5

Zjets_BFilter: &Zjets_BFilter
  name: Zjets_BFilter
  # pattern: user.bbullard.506196.e8382_e7400_s3681_r13144_r13146_p5278.tdd.PHYSVAL_EMPFlow_jer.23_0_26.v2.1_output.h5/*.h5
  pattern: user.pbhattar.506196.e8382_e7400_s3681_r13144_r13146_p5278.tdd.PHYSVAL_EMPFlow_jer.23_0_26.24-05-16-T173804_output.h5/*.h5

global_cuts:
  train:
    - [eventNumber, "%10<=", 7]
  val:
    - [eventNumber, "%10==", 8]
  test:
    - [eventNumber, "%10==", 9]

inclusive: &inclusive
  name: inclusive
  cuts: []

inclusive2: &inclusive2
  name: inclusive2
  cuts: []

truth_pt: &truth_pt
  name: truth_pt
  cuts:
    - [truthJetPt, ">", 5_000]
    - [truthJetPt, "<", 6_000_000]

# Defines the outputs!
components:
  # Test
  #- region:
  #    <<: *inclusive
  #  sample:
  #    <<: *ttbar_nonallhad
  #  flavours: [bjets]
  #  num_jets: 10_000
  
  - region:
      <<: *inclusive
    sample:
      <<: *ttbar_nonallhad
    flavours: [bjets]
    num_jets: 126_000_000

  - region:
      <<: *inclusive
    sample:
      <<: *ttbar_nonallhad
    flavours: [cjets]
    num_jets: 14_000_000

  - region:
      <<: *inclusive
    sample:
      <<: *ttbar_nonallhad
    flavours: [ujets]
    num_jets: 126_000_000

  - region:
      <<: *inclusive2
    sample:
      <<: *Zjets_BFilter
    flavours: [bjets]
    num_jets: 9_000_000

  - region:
      <<: *inclusive2
    sample:
      <<: *Zjets_BFilter
    flavours: [cjets]
    num_jets: 1_000_000

  - region:
      <<: *inclusive2
    sample:
      <<: *Zjets_BFilter
    flavours: [ujets]
    num_jets: 9_000_000

resampling:
  target: cjets
  method: countup
  sampling_fraction: auto
  variables:
    pt:
      bins: [[0, 200_000, 20], [200_000, 1_000_000, 4], [1_000_000, 6_000_000, 1]]
    #eta:
    #  bins: [[-2.5, 2.5, 10]]


global:
  batch_size: 10_000
  num_jets_estimate: 50_000
  base_dir: /fs/ddn/sdf/group/atlas/d/bbullard/bjr/samples/physval_v2.1/upp/hybrid_allFlavor_resampled_v2
  out_dir: merged
  ntuple_dir: ../../../../../../pbhattar/BjetRegression/TrainingNtuples/tddoutput
  # ntuple_dir: ../../tdd

variables: !include /sdf/home/b/bbullard/bjer/datasets/umami-preprocessing/upp/configs/bjr/bjr_variables_v2.1.0.yaml