ttbar_nonallhad: &ttbar_nonallhad
  name: ttbar_nonallhad
  pattern: user.bbullard.410470.e6337_s3681_r13144_p5169.tdd.PHYSVAL_EMPFlow_jer.23_0_26.v2.1_output.h5/*.h5

Zjets_BFilter: &Zjets_BFilter
  name: Zjets_BFilter
  pattern: user.bbullard.506196.e8382_e7400_s3681_r13144_r13146_p5278.tdd.PHYSVAL_EMPFlow_jer.23_0_26.v2.1_output.h5/*.h5

global_cuts:
  train:
    - [eventNumber, "%10<=", 7]
  val:
    - [eventNumber, "%10==", 8]
  test:
    - [eventNumber, "%10==", 9]

inclusive: &inclusive
  name: inclusive
  cuts: []

inclusive2: &inclusive2
  name: inclusive2
  cuts: []

truth_pt: &truth_pt
  name: truth_pt
  cuts:
    - [truthJetPt, ">", 5_000]
    - [truthJetPt, "<", 6_000_000]

# Defines the outputs!
components:
  # Test
  #- region:
  #    <<: *inclusive
  #  sample:
  #    <<: *ttbar_nonallhad
  #  flavours: [bjets]
  #  num_jets: 10_000
  
  - region:
      <<: *inclusive
    sample:
      <<: *ttbar_nonallhad
    flavours: [bjets]
    num_jets: 90_500_000

  - region:
      <<: *inclusive2
    sample:
      <<: *Zjets_BFilter
    flavours: [bjets]
    num_jets: 9_500_000


resampling:
  target: bjets
  method: none #countup #pdf
  sampling_fraction: 1 #auto
  variables:
    pt:
      bins: [[20_000, 1_000_000, 28]]
    eta:
      bins: [[-2.5, 2.5, 10]]


global:
  batch_size: 10_000
  num_jets_estimate: 10_000
  base_dir: /fs/ddn/sdf/group/atlas/d/bbullard/bjr/samples/physval_v2.1/upp
  out_dir: mixed_ZjetsBFilter-ttbar
  ntuple_dir: ../tdd

variables: !include /sdf/home/b/bbullard/bjer/datasets/umami-preprocessing/upp/configs/bjr/bjr_variables_v2.1.0_lite.yaml